# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.CharField(max_length=300),
        ),
    ]
