# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0002_auto_20160319_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishDiet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fit.Diet')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fit.Dish')),
            ],
        ),
    ]
