# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 18:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0003_dishdiet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='diet',
        ),
    ]
