# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0006_diet_restaurant_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=255)),
                ('restaurant', models.ManyToManyField(to='fit.Restaurant')),
            ],
        ),
    ]
