# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0009_dish_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='diet',
            field=models.ManyToManyField(to='fit.Diet'),
        ),
    ]
